### ISSUE TITLE
Nothing happens in Firefox or Chrome

### ISSUE THREAD

**Issue by torridgristle** [MysteryPancake/Phomeme#1]
In Firefox when using Donkey Kong it just says it's loading the phoneme and it's stuck on this, seems to do nothing. In Chrome it says "Couldn't load donkeykong! Try installing a cross-origin extension." and despite trying 2 different extensions for this it still gives me this error.

What should I do?

**Comment by torridgristle** [comment]
"Loading phone dictionary..." specifically, in Firefox.

**Comment by MysteryPancake** [comment]
I'm not quite sure how you found this page, but it's still a heavy work in progress. The old website has a lot of annoying errors, and the loading error happens quite often. This issue might be due to the website being opened locally. If the website is not hosted on a server, the XMLHttpRequest will fail due to requesting local resources. It will probably print the exact error in the console if this is not the issue.

I'm working on redesigning the website before anyone is supposed to see it, so I wouldn't recommend using it at the moment. When it becomes usable I will update the readme and add documentation.

**Comment by torridgristle** [comment]
It works in Chrome after using http.server in Python3 to start a server, still have the same problem in Firefox though.

**Comment by MysteryPancake** [comment]
The issue on Firefox is due to the regex expression in convert.js.
I would rather make this repository private to avoid people using this at the moment.
There are many more issues which I need to fix before it becomes usable.

**Comment by MysteryPancake** [comment]
It should now work on Firefox and Chrome - again I am still working on this so it's not currently designed for public use
